# Generated by Django 4.2.6 on 2024-01-20 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default='M', max_length=1)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('house_number', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=40)),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles')),
                ('available_leave', models.IntegerField(default=26)),
                ('on_demand_leave', models.IntegerField(default=4)),
                ('parental_leave', models.IntegerField(default=5)),
                ('force_majeure_leave', models.IntegerField(default=2)),
                ('is_manager', models.BooleanField(default=False)),
                ('contract_type', models.CharField(choices=[('1', 'Pełny etat'), ('2', 'Pół etatu')], default='1', max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
