# Generated by Django 4.2.6 on 2024-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_leave',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='profile',
            name='force_majeure_leave',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_demand_leave',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='parental_leave',
            field=models.IntegerField(default=5),
        ),
    ]
