# Generated by Django 4.2.6 on 2024-01-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_available_leave_profile_force_majeure_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(choices=[('1', 'Pełny etat'), ('2', 'Pół etatu')], default='1', max_length=1),
        ),
    ]
