# Generated by Django 4.2.6 on 2024-01-20 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_request',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('1', 'oczekiwanie na rozpatrzenie'), ('2', 'zaakceptowany'), ('3', 'odrzucony')], default='1', max_length=1)),
                ('leave_type', models.CharField(choices=[('1', 'urlop wypoczynkowy'), ('2', 'urlop na żądanie'), ('3', 'urlop opiekuńczy'), ('4', 'urlop z powodu siły wyższej')], default='1', max_length=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
