# Generated by Django 4.2.6 on 2024-01-20 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Oczekiwanie na rozpatrzenie'), ('2', 'Zaakceptowany'), ('3', 'Odrzucony')], default='1', max_length=1)),
                ('leave_type', models.CharField(choices=[('1', 'Urlop wypoczynkowy'), ('2', 'Urlop na żądanie'), ('3', 'Urlop opiekuńczy'), ('4', 'Urlop z powodu siły wyższej')], default='1', max_length=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_of_days', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
