# Generated by Django 4.2.6 on 2024-01-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leave_requests', '0002_alter_leave_request_id_alter_leave_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_request',
            old_name='id',
            new_name='request_id',
        ),
    ]
